In [1]:
import numpy as np

In [2]:
# ques 1
import numpy as np
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# ques 2
arr = np.ones(9)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# ques
import numpy as np
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
np.array(([0,1,2],[3,4,5],[6,7,8]))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
a = np.array(([0,1,2],[3,4,2],[6,7,8]))
res = np.flip(a)  
print(res)

[[8 7 6]
 [2 4 3]
 [2 1 0]]


In [8]:
a = np.array(([0,1,2],[3,4,5],[6,7,8]))
a[a%2==1]

array([1, 3, 5, 7])

In [11]:
x = np.random.randint(1,11,(4,4))
y = np .random.randint(1,11,(4,4))
print(f'the x array are \n{x}')
print(f'the y array are \n{y}')
print('-'*20)
print(f'the sum of array is :\n {x+y}')
print(f'the multiplication of array is :\n{x*y}')

the x array are 
[[10  5  5  1]
 [ 6  9  9  1]
 [ 6 10 10  6]
 [ 8  6  7 10]]
the y array are 
[[ 8  3  6  6]
 [10  6  5  2]
 [ 2  6  8  9]
 [ 5  1  8  5]]
--------------------
the sum of array is :
 [[18  8 11  7]
 [16 15 14  3]
 [ 8 16 18 15]
 [13  7 15 15]]
the multiplication of array is :
[[80 15 30  6]
 [60 54 45  2]
 [12 60 80 54]
 [40  6 56 50]]


In [13]:
b = np.random.randint(0,11,(5,5))
print(b)
bmin,bmax = x.min(),x.max()
print(f'the maximum value is : {bmax}')
print(f'the minimum value is : {bmin}')

[[ 7  0  4  1  9]
 [ 6  6  8  4  4]
 [ 3  9  7  4  8]
 [ 6  1 10  6  7]
 [ 0 10  7  4  0]]
the maximum value is : 10
the minimum value is : 1


In [14]:
x = np.array(([[1,0,1],[1,0,1]],[[1,0,1],[1,0,1]]))
print(x)

[[[1 0 1]
  [1 0 1]]

 [[1 0 1]
  [1 0 1]]]


In [16]:
arr = np.array([3,3,4,5,6,5,6,4])
res = np.unique(arr)
print(res)

[3 4 5 6]


In [17]:
x = np.array(([[1,2,3],[5,2,6]],[[7,3,5],[7,4,3]]))
a = x[x%2==0]
print(a)
r = np.unique(a)
print(r)

[2 2 6 4]
[2 4 6]


In [18]:
x = np.array(([[1,2,3],[5,2,6]],[[7,3,5],[7,4,3]]))
a = np.flip(x)
print(a)

[[[3 4 7]
  [5 3 7]]

 [[6 2 5]
  [3 2 1]]]


In [21]:
initial_array = np.array(([[1,1,1,2],[2,2,2,3],[3,3,3,4]],[[1,1,1,2],[2,2,2,3],[3,3,3,4]]))
index = 0 
initial_shape = initial_array.shape
reversed = np.empty(shape=initial_shape)
for inner_array in initial_array:
    reversed[index]=np.fliplr(inner_array)
    index +=1
print(f'the initial array is :- \n{initial_array}')
print(f'the reversed array is : - \n{reversed}')

the initial array is :- 
[[[1 1 1 2]
  [2 2 2 3]
  [3 3 3 4]]

 [[1 1 1 2]
  [2 2 2 3]
  [3 3 3 4]]]
the reversed array is : - 
[[[2. 1. 1. 1.]
  [3. 2. 2. 2.]
  [4. 3. 3. 3.]]

 [[2. 1. 1. 1.]
  [3. 2. 2. 2.]
  [4. 3. 3. 3.]]]


In [22]:
matrix = np.diag([1,4,9,0,1,2,3])
print(matrix)

[[1 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 9 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 3]]
